name: Feature
description: Propose a new feature
title: "[Feature]: "
labels: ["feature"]
projects: ["unimator/2"]
assignees:
  - unimator
body:
  - type: textarea
    attributes:
      label: Content here